rocq-community/coq-ext-lib

Makefile
examples/Makefile
examples/WithDemo.v
theories/Makefile

Fixes to build ext-lib under MacOS using Coq-8.4.
Please note that OPAM package here https://github.com/coq/opam-coq-archive/tree/master/released/packages/coq-ext-lib/coq-ext-lib.0.9.0 even though marked as compatible with Coq-8.4 fails to install. Once your source is fixed I will ping them to update the packet to use new version.

Macos coq8.4 build

---

theories/Core/Type.v

This avoids "Universe.unbound Top.XX" problem in trunk and 8.5+new universe check algorithm.
I'm not sure if this is a Coq bug or not, but this fixes the jsCoq build of mirror-core.

Add missing type annotation.

---

theories/Data/Monads/WriterMonad.v

This merge request includes 3 distinct but related additions:
1. `mapWriterT` definition modeled after one in Haskell
2. `castWriterT` definition. A special case of `mapWriterT` where mapping function is identity. Basically, it swaps Monoid in a monad keeping same types for state and carrier.
3.  `writer` monad definition modeled after one in Haskell. Additionally `mapWriter` and `castWriter` definitions provided based on their transformer equivalents.
All definitions are organized into separate sections, so you can cherry-pick. 
I have not specified universes implicitly since I am not comfortable with Universe Polymorphism. I tried it, but using `mapWriter` was causing "universe inconsistency" errors. Perhaps I did it wrong?

mapWriter, castWriter

---

examples/ConsiderDemo.v
theories/Data/ListFirstnSkipn.v

This backward-compatible patch prepares ext-lib for
https://github.com/coq/coq/pull/7878

Prepare for porting to lia

---

theories/Structures/Monad.v

Previously every bind got printed using this new notation, even if the pattern is only a variable.
Side question: does development happen on branch `master` or `v8.8`?

Display the new ' _ <- _ ;; _ notation only with nontrivial patterns

---

theories/Data/HList.v

We have to use explicit universes in order to avoid having additional
floating universes.

Remove algebraic universes in match return clauses.

---

theories/Data/HList.v

I didn’t find functions to go from `hlist`s to `list`s and conversely, so I created these. I tried to be consistent with the general style of the library.

Adding functions to go from lists to hlists and conversely.

---

theories/Data/Member.v

In the previous PR, we had this discussion that the parameter of `hlist_gen` should take either a `member` or a `In` as argument. I chose `member` as one can convert it into an `In` (whilst the convert doesn’t hold). I however didn’t find this lemma in the development. Here it is.

Adding a way to convert [member]s into [In]s.

---

theories/Structures/Monad.v

Fixes #56 
Do you have any objections to also reducing the other 100 level notations so they bind more strongly than `=`?

Make >=> right associative

---

theories/Data/Monads/EitherMonad.v
theories/Data/Monads/IdentityMonad.v
theories/Data/Monads/OptionMonad.v

Related to #58 (for mkStateT)
I wonder they should really be maximally inserted...

Implicit arguments for mkOptionT, mkEitherT, mkIdentT

---

theories/Structures/Applicative.v
theories/Structures/Functor.v
theories/Structures/Monad.v

Declaring two notations with different associativities but the same
precedence level leads to a conflict. Instead we establish the
convention that even precedence levels are for left-associative
notations, and odd precedence levels are for right-associative notations.
Fixes #66.

Fix inconsistent notation levels associativity

---

theories/Core/Type.v
theories/Data/List.v
theories/Data/POption.v
theories/Data/PPair.v
theories/Data/PreFun.v
theories/Programming/Show.v
theories/Structures/Applicative.v
theories/Structures/CoFunctor.v
theories/Structures/FunctorLaws.v
theories/Structures/Monad.v
theories/Structures/Monoid.v

Not backwards compatible, but could be made so with a bit of work. Questions about this below.
I have trouble understanding the design choices underlying ext-lib, maybe the changes of this PR are not the right ones.
- First, it seems that the `Polymorphic` qualifier is used a lot, where the polymorphic universe option could be set instead. Is that a conscious design choice, or is it a remnant of the time when universe polymorphism was still very experimental? This forces me to put polymorphic attributes on sections.
- Some sections are willingly mixing polymorphic and monomorphic data, seemingly. Is that on purpose? I had to extrude them.

Fix w.r.t. coq/coq#10441.

---

theories/Core/Type.v
theories/Data/List.v
theories/Data/POption.v
theories/Data/PreFun.v
theories/Programming/Show.v
theories/Structures/Applicative.v
theories/Structures/CoFunctor.v
theories/Structures/FunctorLaws.v
theories/Structures/Monad.v
theories/Structures/Monoid.v

Follow up from the discussion at the end of #65 
Also fixes coq/opam-coq-archive#939
The main point is to make this build again on 8.9, but I also did some clean up in the affected files (I only changed files touched by #65 but the same thing could be done throughout).
- Removed `Polymorphic` keywords, which is now implicit. Furthermore `Universe` has different semantics when this is on.
- Explicit universe quantification. The proof `RelDec_Correct_eq_list` and a few definitions (`Injective` instances in `POption`) needed a little fixing to avoid introducing spurious universes. The only exception is `Show`, which I'd rather rewrite or deprecate altogether (in favor of a more structured representation than strings), so I only did the minimum.

Replace section annotations with global Set Universe Polymorphism

---

Makefile
examples/Makefile

- `cleanall` also cleans `.aux` files
- do nothing if no makefile exists
- ~~`$(RM)` is `rm -f` (I admit I don't actually see a reason to prefer this macro over the expanded form...)~~

Makefile: improve clean command

---

theories/Data/Vector.v

After coq/coq#9918, vector was no-longer template polymorphic.  This
backwards-compatible commit fixes that.
Note that this is required for mirror-core to build with Coq v8.10 without universe errors.

Make vector template-polymorphic again

---

theories/Structures/Applicative.v

Applicative is Functor

---

theories/Programming/Extras.v

overlay for coq/coq#11992
it's backward-compatible, can be merged now.

[coq] use ListNotations explicitly

---

examples/ConsiderDemo.v

coq/coq#12008 introduces a new `Bool.ltb` with potential conflicts with `Nat.ltb` when `ltb` is not qualifed enough.

overlay for coq/coq#12008

---

README.md
meta.yml

Includes a move from the Gitter badge to the Zulip badge in README.
Note: we are not there yet regarding the CircleCI template nor the
opam file to allow regenerating these files blindly, but the
coq-ext-lib/templates fork no longer contains anything that cannot be
achieved with coq-community/templates.

Regenerate files from latest templates.

---

theories/Data/Fun.v

https://github.com/coq-community/coq-ext-lib/issues/88
- `Functor_Fun` and `Applicative_Fun` instances are global
- Removed duplicate instance for `Functor (Fun A)`

Fun functors visibility

---

Makefile

For instance in Coq's CI we don't setup submodules (it's faster to just download the tarball from github)

Don't fail if coqdocjs not present

---

theories/Structures/Monad.v

Following a request from @alxest, we added in the itree library this notation to be able to add type annotations to binders in monadic notations. It could be great to mirror this in ext-lib.
The notation uses a back-tick to avoid breaking other type annotations.
See: https://github.com/DeepSpec/InteractionTrees/issues/174
Best,
Yannick

Bind notation allowing for type cast annotations of variables

---

examples/Notations.v
examples/_CoqProject
theories/Structures/Monad.v

Closes #95 
Inspired by the notation introduced by OCaml 4.08, we propose to
introduce a new notation following the same principle.
```coq
let* x := p in q
```
is strictly equivalent to
```coq
x <- p;; q
```

Add the let* monadic notation

---

.gitignore
theories/Programming/Extras.v

and deprecate `curry` and `uncurry` for future Coq standard library that include them.

Extras: remove duplicated definition

---

theories/Structures/Monad.v

Deprecate `<-` in favor of `let*`, as discussed in #97, step 1.

Revert backtick notation in #93

---

examples/StateGame.v

Doing some "smoke tests" on the Coq platform I found that the StateGame.v example no longer works - i think cause of changes in recursive requires in Coq. This PR provides a simple fix.

Fix StateGame.v example

---

examples/StateTMonad.v
examples/_CoqProject
theories/Data/Monads/StateMonad.v

Because `Monad_stateT` requires a monad argument, it can in some situations create infinite loops in typeclass resolution. My minimized example of the problem:
```
Require Import Structures.Monad.
Require Import Data.Monads.StateMonad.
Class A (proj : nat -> Type):=
{ m : Type -> Type;
x : m (proj 1);
}.
Definition hangs {proj} {a : A proj} {monad : Monad.Monad m} : m (proj 1) := ret x. (* infinite loop *)
```
The `hangs` definition is not properly typed (it has type `m (m (proj 1)`), but I'd still prefer to get a typeclass-resolution error here than to get an infinite loop. The trace from `Typeclasses Debug` is:
```
Debug: 1: looking for (A ?proj) with backtracking
Debug: 1.1: exact a on (A ?proj), 0 subgoal(s)
Debug: Finished run 1 of resolution.
Debug: 1: looking for (A ?proj) with …
```

Make Monad_stateT a local instance

---

theories/Structures/Monad.v

Closes #97 
This actually reverts and improves a change in #99 (i.e., the ability to add type signatures in bindings was also removed from `let*`; this PR adds it back, in a terser fashion).
I think the main thing left in that issue to resolve was:
> Should we remove `let* notation (which has 0 users) as well?
And I don't think so.
- It was only just added.
- IMO `let* _ := _ in _` is much nicer to the point that I would recommend always using this style. Maybe it clashes with a Scheme convention, but OCaml gives a precedent for this notation. And in PLT "let" is in fact closely related to monads.
If I am guessing correctly, the notation `_ <- _ ;; _` comes from trying to emulate Haskell's `do`-notation, but a crucial difference is that in Haskell it is a much less ambiguous syntax …

Monad: Allow patterns in 'let*' notation

---

theories/Data/ListNth.v

In an effort https://github.com/coq/coq/pull/13986 to streamline Coq's `List.v`, dependencies on `Arith` modules are removed.
Therefore, importing `List` will not provide `Arith` functionality. Resulting issues are fixed by this PR.

Fix for Coq PR 13986

---

theories/Data/String.v

Deprecation commands are not supported by 8.8, thus commenting out.

String: prefer stdlib

---

theories/Data/Map/FMapAList.v

to utilize Coq standard library

FMapAList: add alternative definition

---

examples/ConsiderDemo.v
theories/Data/HList.v
theories/Data/ListNth.v
theories/Data/Nat.v
theories/Data/String.v
theories/Programming/Show.v

We remove some Arith files and NPeano after deprecation.

Adapt to Coq/Coq#18164

---

theories/Data/Monads/EitherMonad.v
theories/Data/Monads/OptionMonad.v
theories/Structures/Applicative.v
theories/Structures/Functor.v
theories/Structures/Monad.v
theories/Structures/MonadLaws.v
theories/Structures/Traversable.v

Not sure why the definition of `sequence` breaks...

Add Hint Mode to Functor, Applicative, Monad

---

.gitignore
dune-project
examples/dune
theories/Generic/Ind.v
theories/dune

This is the minimal change required to be integrate `coq-ext-lib` in a dune workspace.
What is not included:
- Testing dune compilation in CI.
- Support for editors while compiling with `dune`.

Support compilation using [dune].

---

examples/ConsiderDemo.v
theories/Core/Decision.v
theories/Core/EquivDec.v
theories/Data/HList.v
theories/Data/List.v
theories/Data/ListFirstnSkipn.v
theories/Data/ListNth.v
theories/Data/Nat.v
theories/Data/PreFun.v
theories/Data/SigT.v
theories/Data/String.v
theories/Programming/Show.v
theories/Recur/Measure.v
theories/Structures/EqDep.v
theories/Structures/FunctorLaws.v
theories/Tactics/EqDep.v

Adapt to https://github.com/coq/coq/pull/19530
This is an adaptation in anticipation of the day the temporary backward compatibility introduced in the upstream PR will be removed (probably a few years in the future).
Merging this is not required for the upstream PR, you can do whatever you want with it.

Adapt to https://github.com/coq/coq/pull/19530
